# PKI Chain Configuration

[blockchains]
certificate_path = "data/certificates"
private_key_path = "data/private_keys"
crl_path = "data/crl"

[key_exports]
app_key_path = "key/app.key"
app_cert_path = "certificate/app.crt"

[server]
comm_sock = "/tmp/comm_server.sock"
setup_sock = "/tmp/setup_server.sock"

[root_ca_defaults]
root_ca_common_name = "MenaceLabs Root CA"
root_ca_organization = "MenaceLabs"
root_ca_organizational_unit = "CY"
root_ca_locality = "Sao Jose dos Campos"
root_ca_state = "SP"
root_ca_country = "BR"
root_ca_validity_days = 3650

[admin_ca_defaults]
admin_ca_common_name = "MenaceLabs Admin Interm CA"
admin_ca_organization = "MenaceLabs"
admin_ca_organizational_unit = "CY"
admin_ca_locality = "Sao Jose dos Campos"
admin_ca_state = "SP"
admin_ca_country = "BR"
admin_ca_validity_days = 1825
